/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Desktop;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import logica.GenerarMatriz;
import logica.Simplex;

/**
 *
 * @author diego
 */
public class InterfazSimplex extends javax.swing.JFrame {

    private Simplex simplex;
    private GenerarMatriz gmatriz;
    private int contEcuac;
    private Object[] nombres;
    private String detalles;

    /**
     * Creates new form InterfazSimplex
     */
    public InterfazSimplex() {
        initComponents();
        inicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextFieldFuncion = new javax.swing.JTextField();
        jButtonAnadirFuncion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFunciones = new javax.swing.JTextArea();
        jCheckBoxValEcua = new javax.swing.JCheckBox();
        jCheckBoxFunObj = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();
        jLabelMensajes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMuestraDatos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRespuesta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(189, 189, 227));

        jTextFieldFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFuncionMouseClicked(evt);
            }
        });

        jButtonAnadirFuncion.setText("AÑADIR");
        jButtonAnadirFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirFuncionActionPerformed(evt);
            }
        });

        jTextAreaFunciones.setColumns(20);
        jTextAreaFunciones.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFunciones);

        jCheckBoxValEcua.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxValEcua.setText("Nro Ecuaciones Válido ");
        jCheckBoxValEcua.setEnabled(false);

        jCheckBoxFunObj.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxFunObj.setText("Función Objetivo");
        jCheckBoxFunObj.setEnabled(false);
        jCheckBoxFunObj.setHideActionText(true);

        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.setEnabled(false);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelMensajes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMensajes.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabelMensajes.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMensajes.setText("********************************************");

        tablaMuestraDatos.setAutoCreateRowSorter(true);
        tablaMuestraDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMuestraDatos.setCellSelectionEnabled(true);
        tablaMuestraDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tablaMuestraDatos);

        jTextAreaRespuesta.setColumns(20);
        jTextAreaRespuesta.setRows(5);
        jScrollPane3.setViewportView(jTextAreaRespuesta);

        jButton1.setText("DETALLES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jTextFieldFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonAnadirFuncion))
                            .addComponent(jCheckBoxValEcua)
                            .addComponent(jCheckBoxFunObj))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonCalcular)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(151, 151, 151))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelMensajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnadirFuncion))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxFunObj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxValEcua)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(67, 67, 67))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(jTextFieldFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonAnadirFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBoxValEcua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBoxFunObj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelMensajes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jMenuItem1.setText("nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicial() {
        simplex = new Simplex();
        gmatriz = new GenerarMatriz();
        contEcuac = 0;
        jLabelMensajes.setText("INGRESE LA FUNCION OBJETIVO");
        nombres = new Object[0];
        detalles = "";
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        inicial();
        reset();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonAnadirFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirFuncionActionPerformed
        // TODO add your handling code here:
String areaTexto = jTextAreaFunciones.getText();
        try {
            String cadena = jTextFieldFuncion.getText();
            AnalizadorCadenas analizador = new AnalizadorCadenas();
            if (jCheckBoxFunObj.isSelected()) {
                analizador.analizador(cadena);
                gmatriz.anadirFuncion(analizador);
                contEcuac++;
                crearNombresColumna();
                if (contEcuac >= (gmatriz.getMatriz()[0].length) / 2 - 1) {
                    jCheckBoxValEcua.setSelected(true);
                    jLabelMensajes.setText("LISTO PARA CALCULAR");
                    jButtonCalcular.setEnabled(true);
                    llenarTabla();
                }
                areaTexto += "Ecuación " + contEcuac + " :\t" + cadena + "\n";
                jLabelMensajes.setText("INGRESE ECUACIONES..");
            } else {
                analizador.analizador(cadena);
                areaTexto += "Función Objetivo: \t" + cadena + "\n";
                gmatriz.generarMatriz(analizador);
                jCheckBoxFunObj.setSelected(true);
                jLabelMensajes.setText("INGRESE ECUACIONES..");
                crearNombresColumna();
            }
            jTextAreaFunciones.setText(areaTexto);
        } catch (Exception e) {
            System.out.println("XXXXXXXX");
        }
    }//GEN-LAST:event_jButtonAnadirFuncionActionPerformed

    private void crearNombresColumna() {
        //crear los nombres de columna
        nombres = new Object[gmatriz.getMatriz()[0].length];
        //Obtner Variables de decisión 
        int varDes = gmatriz.getNrovaribles();
        //Añadir Z
        nombres[0] = "Z";
        //Añadir R
        nombres[nombres.length - 1] = "R";
        //Anadir X
        for (int i = 1; i <= varDes; i++) {
            nombres[i] = "X" + i;
        }
        //Añadir H
        for (int i = varDes + 1, k = 1; i < nombres.length - 1; i++, k++) {
            nombres[i] = "H" + k;
        }
    }
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        simplex = new Simplex(gmatriz.getMatriz());
        int n = 1;
        while (!simplex.varDesicionCero(n)) {
            detalles += simplex.imprimirMatriz();
            n++;
        }
        jTextAreaRespuesta.setText(simplex.imprimirRespuesta());
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void llenarTabla() {
        int tamanio = gmatriz.getMatriz()[0].length;
        Object[][] datos = new Object[gmatriz.getMatriz().length][tamanio];
        for (int i = 0; i < gmatriz.getMatriz().length; i++) {
            for (int j = 0; j < tamanio; j++) {
                datos[i][j] = gmatriz.getMatriz()[i][j];
            }
        }
        TableModel tm = new DefaultTableModel(datos, nombres);
        tablaMuestraDatos.setModel(tm);
    }
    private void jTextFieldFuncionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFuncionMouseClicked
        // TODO add your handling code here:
        jTextFieldFuncion.setText("");
    }//GEN-LAST:event_jTextFieldFuncionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Detalle detalle = new Detalle();
        String texto = "";
        if (jButtonCalcular.isEnabled()) {
            texto = "  **************   MATRIZ INICIAL   ***************" + "\n";
            for (Object object : simplex.getDetalles()) {
                texto += object;
            }
            detalle.getjTextAreaDetalles().setText(texto);
            jDesktopPane1.add(detalle);
            detalle.show();
        } else {
            texto=""
                    + "INSTRUCCIONES+\n"
                    + "1.- Al inicio, necesariamente hay que ingresar la función objetvio, eje.\n"
                    + "z=#x#+#x#+#xn \n"
                    + "z=3x1+5x2 \n"
                    + "2.- Se ingresan las inecuaciones, para representar a (menor igual) se utiliza (<) ejem.  \n"
                    + "#x#+#x#<# \n"
                    + "3x1<8   :  tres equis uno menor que ocho";
            detalle.getjTextAreaDetalles().setText(texto);
            jDesktopPane1.add(detalle);
            detalle.show();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset() {
        jTextAreaFunciones.setText("");
        jCheckBoxFunObj.setSelected(false);
        jCheckBoxValEcua.setSelected(false);
        jButtonCalcular.setEnabled(false);
        jTextFieldFuncion.setText("");
        TableModel tm = new DefaultTableModel();
        tablaMuestraDatos.setModel(tm);
        jTextAreaRespuesta.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSimplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnadirFuncion;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JCheckBox jCheckBoxFunObj;
    private javax.swing.JCheckBox jCheckBoxValEcua;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelMensajes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaFunciones;
    private javax.swing.JTextArea jTextAreaRespuesta;
    private javax.swing.JTextField jTextFieldFuncion;
    private javax.swing.JTable tablaMuestraDatos;
    // End of variables declaration//GEN-END:variables
}
